# Install all security, critical, and rollup updates
- win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
  register: update_state


- name: Reboot the Machine if required
  win_reboot:
  when: update_state.reboot_required
  ignore_errors: yes
