---

# Mount role
# Mounting devices on specific mount points and adding them to fstab.
#
# Actions:
# - Mounting devices
#
# Compatibility version: 2.2.1
#
# Variable:
# Mandatory
# - mount_path (mount point, if it does not exist it will be created)
# - mount_dev (device)

- name: Mounting volume {{ mount_dev }} on {{ mount_path }}
  mount:
    name: "{{ mount_path }}"
    src: "{{ mount_dev }}"
    fstype: xfs
    state: mounted
