---

# Prep role
# Preparing OS for deployment purpose via ansible. This role must be run as
# a first.
#
# Actions:
# - Installing packages required by modules
# - Flushing existing default connections if 'prep_flush' variable is defined
# - Installing/uninstalling  EPEL repository if 'prep_epel' variable is defined
# - Installing sysadmins packages if 'prep_epel' variable is defined
# - Upgrading packages if 'prep_upgrade' variable is defined
# - Configuring SELinux if 'prep_selinux' variable is defined
# - Enabling/disabling firewall if 'prep_firewall' variable is defined
# - Installing mcelog if 'prep_mcelog' variable is defined
#
# Compatibility version: 2.3
#
# Variables:
# Optional
# - prep_flush (to flush existing default connections)
# - prep_omit (required by prep_flush, coma separated list of connections that
#              have to be removed, a connection using by ansible must to be
#              specified here)
# - prep_epel (to install epel repository if true or to uninstall the reposotory
#              if false)
# - prep_upgrade (to upgrade packages, '*' is available to upgrade all packages)
# - prep_selinux (to configure SELinux mode)
# - prep_firewall (to enable firewall if true or to disable it if false)
# - prep_mcelog (to install mcelog if true)
#
# Modules:
# - flush (to flush existing default connections)

- name: Installing NetworkManager glib
  yum:
    name: NetworkManager-glib
    state: present

- name: Flushing existing connections
  flush:
    omit: "{{ prep_omit }}"
  when: prep_flush is defined and prep_flush and prep_omit is defined

- name: Installing epel
  yum:
    name: epel-release
    state: present
  when: prep_epel is defined and prep_epel

- name: Uninstalling epel
  yum:
    name: epel-release
    state: absent
  when: prep_epel is defined and not prep_epel

- name: Install basic sysadmin packages
  yum: name={{ item }} state=latest
  with_items:
    - tcpdump
    - bind-utils
    - net-tools
    - iotop
    - wget
    - vim
    - iperf
    - traceroute
    - policycoreutils-python
    - setools-console
    - sysstat
    - iptraf
    - lsof
    - mtr    
  when: prep_epel is defined and prep_epel

- name: Upgrade packages
  yum:
    name: "{{ prep_upgrade }}"
    state: latest
  when: prep_upgrade is defined

- name: Setting selinux
  selinux:
    policy: targeted
    state: "{{ prep_selinux }}"
  when: prep_selinux is defined

- name: Enabling firewall
  systemd:
    name: firewalld
    enabled: yes
    state: started
  when: prep_firewall is defined and prep_firewall

- name: Disabling firewall
  systemd:
    name: firewalld
    enabled: no
    state: stopped
  when: prep_firewall is defined and not prep_firewall

- name: Installing mcelog
  yum:
    name: mcelog
    state: present
  when: prep_mcelog is defined and prep_mcelog

- name: Adding log path to mcelog
  lineinfile:
    dest: /usr/lib/systemd/system/mcelog.service
    regexp: '^ExecStart'
    line: "ExecStart=/usr/sbin/mcelog --ignorenodev --daemon --syslog --logfile=/var/log/mcelog"
    state: present
  when: prep_mcelog is defined and prep_mcelog

- name: Starting mcelog
  systemd:
    name: mcelog.service
    daemon_reload: yes
    state: restarted
    enabled: yes
  when: prep_mcelog is defined and prep_mcelog
