- name: Join the machine to domain
  win_domain_membership:
    dns_domain_name: "{{ windows_domain_name }}"
    hostname: "{{ ansible_nodename|regex_replace('.$', '') }}"
    domain_admin_user: "{{ windows_domain_admin_user }}"
    domain_admin_password: "{{ windows_domain_admin_password }}"
    state: domain
  register: domain_join
  when: windows_domain_join is defined and windows_domain_join


- name: Remove the machine from the domain
  win_domain_membership:
    domain_admin_user: "{{ windows_domain_admin_user }}"
    domain_admin_password: "{{ windows_domain_admin_password }}"
    state: workgroup
    workgroup_name: WORKGROUP
  register: domain_remove
  when: windows_domain_join is defined and not windows_domain_join


- name: Reboot the Machine after have joined the domain
  win_reboot:
  when: domain_join.reboot_required is defined and domain_join.reboot_required


- name: Reboot the Machine after have left the domain
  win_reboot:
  when: domain_remove.reboot_required is defined and domain_remove.reboot_required

